version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hackaton-bbva2021"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dnbx4yq444km"
s3_prefix = "hackaton-bbva2021"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
